server:
  port: 1050
spring:
  datasource:
    password: qwsA9KHa3QgE+kybNu=_g-h
    url: jdbc:postgresql://104.236.67.87:5432/mini-market
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true